### ISSUE TITLE
Recommendations for Pointer Handlers

### ISSUE THREAD

**Issue by jbizovi** [UNC-Project-Open-AAC/OS-DPI#108]
After our call today, Franchesca, Todd, and I have recommendations we'd like to propose for renaming the pointer handler types.

Current Names: Pointer Up, Pointer Down, Pointer Enter, Pointer Leave
Proposed Names: Release, Press, Hover On/Over (we're split on which of those to use), Hover Off

**Comment by sofia-bg** [comment]
@lageist

**Comment by lageist** [comment]
@jbizovi @sofia-bg - thanks, appreciate thinking about naming conventions here. I'm thinking part of our challenge is making distinctions between the mapping of the low-level browser events (like what's defined in the pointer handler types) and the event(s) that trigger the defined action(s) (e.g., right now everything is 'Press' in the Action tab, so potentially problematic to use 'press' in the lower-level name?).

**Comment by gbishop** [comment]
"press" is going away in the next release. That column in "Actions" will be
deleted. If you need access to the event type you'll be able to get it in
the conditions but I don't expect that to happen much.
