### ISSUE TITLE
github.io site not fully reloading

### ISSUE THREAD

**Issue by gbishop** [UNC-Project-Open-AAC/OS-DPI#115]
Users apparently have to force refresh to get the latest code.

**Comment by aetkie** [comment]
To force refresh, I used this process:
Mac users: Shift-Command-R
PC users:  Control - Shift - F5

**Comment by aetkie** [comment]
@gbishop, after a force refresh, should the homepage view change? Loaded designs remain?

**Comment by gbishop** [comment]
Nothing should change about the appearance and your design should still be
there.
