### ISSUE TITLE
Unexpected End of JSON Input Error

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#127]
Attempting to import previous design file saved [here](https://github.com/UNC-Project-Open-AAC/OS-DPI/blob/5a32eea83995e1651bf7eda434846ad843c2ae63/Designs%20In%20Progress/LG_Explore/top_right_nav_102122.osdpi).

**Comment by gbishop** [comment]
The layout of that file is empty. Looks like it was created back in October. I'm guessing we had a bug in that version.

If you have it loaded into your app you may be able to export it again. Otherwise, I fear the content is lost.
