### ISSUE TITLE
Refresh required to use Save sheet function

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#128]
'Save sheet' not working until browser manually refreshed.

**Comment by gbishop** [comment]
I'll need an example of how to reproduce this if possible. I can import a
design then save the sheet without error.

**Comment by lageist** [comment]
Seemed to happen after I'd been working for a while. I'll try to recreate.

**Comment by gbishop** [comment]
I think this should be fixed. Reopen if you see it again.
