### ISSUE TITLE
Error loading media - .png symbol files

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#130]
Error message when attempting to 'Load media' from [here](https://drive.google.com/open?id=1Iv256gO3TWerqnyoIPMKHtVXlMqj4VpU&authuser=lageist%40gmail.com&usp=drive_fs)

Error Message: 

Can't open this file 

**unc-project-open-aac.github.io** can't open files in this folder because it contains system files

**Comment by lageist** [comment]
above media loads fine when directory copied to my desktop and loaded from there.

**Comment by gbishop** [comment]
I think this is a browser security requirement that we won't be able to
change.

**Comment by gbishop** [comment]
How did you attempt to load the image? I guess you have a google drive app
on your computer?

**Comment by lageist** [comment]
Yes, I have the Google Drive app that allows me to navigate to all my directories via the Finder. I attempted to load these images by navigating thought the Finder to My Drive/Project OPEN (2020-2025)/OS-DPI/UI_Projects/Symbols/PCS

**Comment by gbishop** [comment]
If Chrome complains I'm guessing we cannot fix it. It would be worth a note
in the documentation.
