### ISSUE TITLE
Reload Sheet

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#131]
Error message when attempting to use 'Reload sheet'

Error message: t.arrayBuffer is not a function

**Comment by gbishop** [comment]
I can't reproduce. Please tell me more.

**Comment by lageist** [comment]
I'll snag a video next time I'm working. This error presented every time I attempted to use 'Reload Sheet' while I was making changes to content in an open spreadsheet.

**Comment by gbishop** [comment]
I think I see the problem here. Will push a new version soon.
