### ISSUE TITLE
Make display selectable 

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#134]
Can we make the display a selectable origin? Many designs eliminate the need for a separate 'Speak' button by assigning the action to the display.

**Comment by gbishop** [comment]
Yes, this will be straightforward. It will require adding a Name field to
the display component to use as the Origin in actions. Do you need info on
the word that was touched? Or is anywhere ok?

**Comment by lageist** [comment]
Awesome. For the most common use cases, anywhere is fine. But could be beneficial to be able to select a specific word, if that's possible.

**Comment by gbishop** [comment]
This should work now. Checkout out display_test.osdpi in Designs In Progress for an example.
