### ISSUE TITLE
Action Only Allowing Origin

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#144]
Trying to make a [new layout](https://github.com/UNC-Project-Open-AAC/OS-DPI/blob/main/Designs%20In%20Progress/IDD01%20Access%20Solutions/Clear_Dwell_Different/Clear_Dwell_Different.osdpi) and when I add an action it is letting me name an origin but not enter information for conditions state or new value. For old layouts I imported I am able to enter text into those areas. 

![Screen Shot 2023-01-09 at 1 54 50 PM](https://user-images.githubusercontent.com/92817124/211385775-2b397779-4baf-4f84-876d-86a153bbc00d.png)

**Comment by gbishop** [comment]
This is issue #137. You have to Add the conditions and update. I'll making having one each the default.

**Comment by sofia-bg** [comment]
I am not following... I see the issue 137 about making blank but I am not sure what that means I am supposed to do after I add an action and type in origin.

**Comment by gbishop** [comment]
Click add and it should have condition and update

**Comment by gbishop** [comment]
Yes that needs work
