### ISSUE TITLE
How to load an unsaved design

### ISSUE THREAD

**Issue by aetkie** [UNC-Project-Open-AAC/OS-DPI#150]
<img width="595" alt="Screenshot 2023-01-11 at 8 37 04 PM" src="https://user-images.githubusercontent.com/113473933/211955267-66427244-be12-4125-b0cb-516c5880912a.png">

While working on a design, the browser stopped responding. I closed the tab, reopened OS-DPI and now the design says "Not saved" and the Unload button is grayed out. How do I get the design to reload without losing what I have created?

**Comment by gbishop** [comment]
Click the name. It is a link.

**Comment by aetkie** [comment]
I see that. But I am noticing that if I try to click on a link, and it does not open, then several other designs that are loaded will also not open. I am solving this by closing the tab, reopening OS-DPI, and trying again. Unloading links that will not open but risking losing unsaved designs.

**Comment by gbishop** [comment]
That is a bug. Can we meet on zoom so I can track it down? Anytime works
for me

**Comment by aetkie** [comment]
@gbishop fixed the bug. 

I forced the browser to reload the page using the following steps:
Hold down Shift and click the Reload button.
Or Hold down Command, Shift and click the 'R' key.

Closing this issue.
