### ISSUE TITLE
empty conditions field

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#158]
Creating a simple tutorial. Adding an 'Action' includes 'Conditions' field automatically. If Conditions left empty, action not working. If deleted, action works. Seems like it should ignore Conditions if empty? 
![image](https://user-images.githubusercontent.com/91340176/213578922-bb205fad-7bfe-4001-8daa-c80191c1e3ac.png)

**Comment by gbishop** [comment]
Yes! That is clearly a bug. I thought empty ones were ignored. I'll check.

**Comment by gbishop** [comment]
Should be fixed if you reload. Please confirm when you get a chance.

**Comment by lageist** [comment]
Fixed, thanks!
