### ISSUE TITLE
changing grid color

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#161]
Crashed the system when changing the grid color of the single words example ([single words](https://unc-project-open-aac.github.io/OS-DPI/?fetch=examples/updated/grid_ex_1.osdpi) to cobalt blue. 
![Screen Shot 2023-01-20 at 2 17 05 PM](https://user-images.githubusercontent.com/91340176/213786968-3debc232-4224-4a51-986e-216b6343ffcc.png)

**Comment by gbishop** [comment]
I think I've fixed it. If you refresh it should work now.

**Comment by lageist** [comment]
Fixed!
