### ISSUE TITLE
Internal Error popped up 3 times when I was practicing creating a new page

### ISSUE THREAD

**Issue by hsiaotingsu** [UNC-Project-Open-AAC/OS-DPI#163]
When I followed the tutorial to practice creating a new page, an Internal Error popped up 3 times.
I don't remember what happened the first two times.
The third time it happens when I'm done creating the page, I click "Content" to see each column and it pops up.
If I click "Dismiss this dialog", everything returns to normal. But just wondering if this is a problem.

**Comment by gbishop** [comment]
I'm sure it is a problem. The internal error popup includes a link to send
me an email with the details. Please use that. I need that traceback
information.

Thanks for reporting.
gb

**Comment by hsiaotingsu** [comment]
Hi Gary,

Thank you for prompt reply. This is the Error Report.

Error Report

Cannot read properties of null (reading 'stacktrace')

Stack Trace

  *   TypeError: Cannot read properties of null (reading 'stacktrace')
  *   at Object.parse (https://unc-project-open-aac.github.io/OS-DPI/index.20230126T173041.js:1:3150)
  *   at Object.<anonymous> (https://unc-project-open-aac.github.io/OS-DPI/index.20230126T173041.js:10:4348)
  *   at new Promise (<anonymous>)
  *   at Object.fromError (https://unc-project-open-aac.github.io/OS-DPI/index.20230126T173041.js:10:4314)
  *   at window.onerror (https://unc-project-open-aac.github.io/OS-DPI/index.20230126T173041.js:39:103)

Thanks,
Sophie
________________________________
寄件者: Gary Bishop ***@***.***>
寄件日期: 2023年2月10日 上午 08:54
收件者: UNC-Project-Open-AAC/OS-DPI ***@***.***>
副本: Su, Hsiao-Ting ***@***.***>; Author ***@***.***>
主旨: Re: [UNC-Project-Open-AAC/OS-DPI] Internal Error popped up 3 times when I was practicing creating a new page (Issue #163)

您不常收到來自 ***@***.*** 的電子郵件。了解為什麼這點很重要的原因<https://aka.ms/LearnAboutSenderIdentification>

I'm sure it is a problem. The internal error popup includes a link to send
me an email with the details. Please use that. I need that traceback
information.

Thanks for reporting.
gb

**Comment by gbishop** [comment]
Thanks. Unfortunately it is telling me that it ran into an internal error
while trying to report an internal error. I have modified the code in an
attempt to catch the error while reporting the error so that I can see the
original error. Yikes!

Please see if you can trigger the error again and send me that traceback.

I appreciate your patience and help in this.
gb
