### ISSUE TITLE
Logging and Styling with CSS

### ISSUE THREAD

**Issue by jbizovi** [UNC-Project-Open-AAC/OS-DPI#166]
Hi @gbishop, @ManoharGolleru and I were looking into the logging function today, and I'm not sure if we're missing something or not. I opened up and example, added logging, clicked around a bit, then did file save logs. This exported to excel, but is empty every time. Is there something I'm missing?

Also, we are trying to use the css customization to move text around (specifically to the lefthand side) of our buttons on a keyboard. Are you able to help us with this?

**Comment by gbishop** [comment]
Adding the logging component is only one step. The next step is to update
the state name you gave it in an Action. But, at that point, I don't know
what to tell you. Ryan got something working but I don't know what the
Value in the update was supposed to be. I see he added a Log function but
that doesn't appear to do anything but return its arguments.

Let's figure this out. What do you want to log? State variables and field
values are easy. Would that suffice? I can make it work but I have never
gotten an explanation of what you folks want.

CSS customization requires some knowledge of CSS. Didn't you and I change
the font size on one? It's the same idea. I think text-align is the
property you want.

**Comment by ManoharGolleru** [comment]
Hello @gbishop , I have tried updating the state name in the actions but it is giving me a error whenever I click on save logs option. I have attached the screenshot of the error below.
Logging state variables and field values will suffice for now, please let me and @jbizovi know if it works, and thanks for letting us know about the CSS customization.

<img width="560" alt="Screenshot 2023-02-23 113711" src="https://user-images.githubusercontent.com/122695833/220971512-bade9c79-7eaa-4507-8f9f-737ab23c6ef5.png">

**Comment by gbishop** [comment]
I'm not surprised. Send me an example design with logging enabled.

**Comment by ManoharGolleru** [comment]
I have emailed the OSDPI file to you @gbishop

**Comment by jbizovi** [comment]
@gbishop I'm not sure quite how to articulate this, but we want to be able to log everything the user does--any button they press. Does that help?

**Comment by gbishop** [comment]
I think you can do what you need now.
