### ISSUE TITLE
Unable to create filter with VSD

### ISSUE THREAD

**Issue by sagostine** [UNC-Project-Open-AAC/OS-DPI#167]
I am trying to recreate the VSD example with my own pictures. I was able to modify the excel sheet and upload everything but it isn't letting me add filters to the VSD layout like it has in the example. I suspect that's why the actual pictures aren't showing up and all of the boxes are showing up at once. But I am also unsure if I am doing it wrong...let me know! Hopefully with the screen shots this all make sense! 

When I click on grid it does allow me to add a filter. 
![Screenshot 2023-02-24 2 44 16 PM](https://user-images.githubusercontent.com/123391336/221277020-959822e9-8043-46f3-8993-90f4b9ec5486.png)

However when I click on VSD filter is not an option. 
![Screenshot 2023-02-24 2 43 36 PM](https://user-images.githubusercontent.com/123391336/221277023-ffec1d38-c94e-4a7a-9c77-b0c891a454c8.png)

This is what VSD looks like currently. 
![Screenshot 2023-02-24 2 43 54 PM](https://user-images.githubusercontent.com/123391336/221277022-7172d9cf-e469-4c73-9328-924c669e2ca9.png)

**Comment by gbishop** [comment]
Please export your design and send the os-dpi to me.

**Comment by gbishop** [comment]
That is likely a bug.

**Comment by sagostine** [comment]
Just sent it over! Thanks!

**Comment by gbishop** [comment]
I'm away from my computer now. I will look when I can.

**Comment by gbishop** [comment]
Yes. A bug for sure. I'll fix as soon as I can.

**Comment by gbishop** [comment]
I think this is fixed now. Thanks for the report.

**Comment by sagostine** [comment]
It worked!! Thank you!
