### ISSUE TITLE
Background color for VSD

### ISSUE THREAD

**Issue by sagostine** [UNC-Project-Open-AAC/OS-DPI#173]
Hi Gary! 

Would it be possible to add a background color for the VSD? For my adult VSD, there isn't an option to change the VSD background color. Also for some reason it is not letting up attach a picture into this box to show you...

Thanks!

**Comment by gbishop** [comment]
Everything is possible. But I don't understand what you want. Perhaps draw
something in that drawing program we found whose name I can't remember.
Excalidraw?

The photo is the background in a VSD do you mean on either side of the
photo?

**Comment by sagostine** [comment]
Yes! Either side of the photo. Also I realized that that color is connected to the tab control color. I will try again after my next meeting to upload the screen shots!

**Comment by gbishop** [comment]
Yes, I think if you give the tab a background color it should do what you
want.
