### ISSUE TITLE
Ctrl + Shift + ? not working

### ISSUE THREAD

**Issue by aetkie** [UNC-Project-Open-AAC/OS-DPI#179]
When in a design (either new or existing), Ctrl + Shift + ? is not opening the Wiki like it used to.

**Comment by gbishop** [comment]
Alt ? should do it now.

**Comment by aetkie** [comment]
I'm on a Mac...

**Comment by aetkie** [comment]
The option button (⌥ key) shows the keyboard shortcuts now. But adding ? does not take me to the Wiki any longer.

**Comment by gbishop** [comment]
Press Alt release then press ?. I don't have a mac so I may have broken
it...

**Comment by aetkie** [comment]
That's it! You have to release option (alt). Then press ?. Thank you

**Comment by gbishop** [comment]
Refresh and try it now. I think Option-? should work now.
