### ISSUE TITLE
Cues and Add > Add Tab Panel?

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#190]
Having trouble recreating, but with Cues tab open the Add menu offered Tab Panel, which I think is a bug or unintentional. See additional blank tab below, cannot be selected. 
<img width="759" alt="image" src="https://github.com/UNC-Project-Open-AAC/OS-DPI/assets/91340176/a9159c0e-5d11-4547-b36c-0b5024b27d0c">

**Comment by gbishop** [comment]
That is surely a bug

**Comment by gbishop** [comment]
I caused this bug making other changes. I think I've got it fixed.
