### ISSUE TITLE
loading media

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#191]
Trouble getting images to load in a basic grid UI. Played around with exporting to different formats, with and without extensions, all seem to be failing. 
[LG-access.zip](https://github.com/UNC-Project-Open-AAC/OS-DPI/files/11518730/LG-access.zip)

![image](https://github.com/UNC-Project-Open-AAC/OS-DPI/assets/91340176/fc16bb04-7b32-4e76-b9d8-06afbbebc76c)

**Comment by gbishop** [comment]
I'll look into it.

**Comment by gbishop** [comment]
The issue is the names contain spaces. That *should* work but we apparently don't handle that case.

**Comment by gbishop** [comment]
Yes, I see that I broke it when I hacked in the mp4 videos with space separated attributes. My fault. I will fix.

**Comment by gbishop** [comment]
Should be fixed now.
