### ISSUE TITLE
Point and Dwell on VSD

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#198]
I cannot seem to get point and dwell method to work on the VSD. It gives the highlight cue but does not execute the action. It works fine on the grid in the same file here.

[block_to_direct_v1_6_2_23_GB.zip](https://github.com/UNC-Project-Open-AAC/OS-DPI/files/11790818/block_to_direct_v1_6_2_23_GB.zip)

**Comment by gbishop** [comment]
Should be fixed now if you refresh your browser. Thanks for the report.
