### ISSUE TITLE
Make New Cues?

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#202]
I was able to make a new cue (see fill_VSD), but then when I went to the methods it did not appear in the drop down menu as an option. It did work if I set the new cue to be the default. I was able to edit existing cues and those edits were reflected in the design. 

[halves_clear_undo_bottom_speak_close.zip](https://github.com/UNC-Project-Open-AAC/OS-DPI/files/11827154/halves_clear_undo_bottom_speak_close.zip)

**Comment by aetkie** [comment]
I deleted all of the other cues besides fill_VSD. And now it shows up as a choice in the drop down menu for me in Methods. Then I went back to Cues and added one (leaving fill_VSD as default) and it still worked. Not sure why that is...

**Comment by gbishop** [comment]
Excellent detective work their Andrea! I think Sofia must have used Copy/Paste to create fill_VSD. A bug in my implementation of Paste allowed different Cues to have the same internal unique ID. That should not happen; every UID must be unique. 

I'll fix it.

**Comment by sofia-bg** [comment]
I did use copy paste and then didn't think to delete the others since I still wanted to use fill. Playing around with what it looks like to have different cues in different areas... probably won't really use three but just wanted to see what different ones looked like mashed up together.

**Comment by gbishop** [comment]
Fixed. The problem was I was copying the UID which resulted in duplicates.

**Comment by gbishop** [comment]
If you refresh to get the new version, then copy and and paste that Cue that is misbehaving you should be OK.
