### ISSUE TITLE
Cell Background Colors

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#205]
Is there a way that we can have cells have different background colors in the same grid? After field testing yesterday it became apparent being able to imitate the different colors the user has currently would be helpful in testing some of the new features. All white and different symbols is making the UI seem too dissimilar despite words being in the same place. 

Wondering if we could have a #color or #background field in the spreadsheet? Or use a field and declare in the layout? #partofspeech = 'verbs' then button is green, etc.?

**Comment by gbishop** [comment]
We could add a color or background field to the spreadsheet but you can do
this and much more using the Customize facility. The key issue with adding
fields to the spreadsheet is where do you stop? Fonts, position, color,
etc. The Customize component allows tweaking any of these things (and more)
but it does require writing some CSS. You can read about it here:
https://github.com/UNC-Project-Open-AAC/OS-DPI/wiki/Customize

So, suppose you have a field #partofspeech, then you could make all the
verbs green like this:

button[#partofspeech="verb"] { background-color: green; }

**Comment by sofia-bg** [comment]
So on button that can extend to the different parts of the grid, not just buttons that are added through the layout tab? I haven't explore customize yet or even realized it was an option when adding components in layout tab. Will give it a try. 

I guess I just go to spreadsheet because at this point it is the easiest for me to visualize and I am not as up to date with what has been built into newest version.

**Comment by gbishop** [comment]
You can't do it with the spreadsheet now.

The word "button" in the example refers to the HTML button that is used for
everything clickable in the UI, not the Button component we use in Layout.

If you want to restrict the changes to a single component just include that
like

button[#ComponentName="keyboard"][#partofspeech="verb"] { background-color:
green; }

**Comment by sofia-bg** [comment]
Thanks got it working! Will share updated OS-DPI file with customization coding for folks to see later in the week when i get this further along. 
![Screenshot 2023-06-28 at 12 40 40 PM](https://github.com/UNC-Project-Open-AAC/OS-DPI/assets/92817124/de692e8f-9acf-4872-9355-c5ec8109af81)
