### ISSUE TITLE
Display Bar Actions/Functions

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#207]
Can we manipulate the display bar in anyway? I have tried to use actions to see if I can make it speak when selected (a standard feature in AAC devices), but I don't seem to be able to make it happen. 

Thinking to future users we might design for, I am thinking it would be nice to be able to click between words to edit (insert a word between, fix a typo, etc.). I could also see that we might want to be able to scroll back if the words go off the display, or have a setting where once it is full the text gets smaller and all stays on the display? Again maybe an option to be able to have a gesture that the user can choose between these? Maybe long hold and the display gets bigger/smaller...

**Comment by gbishop** [comment]
If you give the display a Name then you can use it as an Origin in an
action.

We do not currently support clicking on words and such though everything is
possible. The larger group should discuss a road map for future features.
We have VERY limited resources for developing new code (that would be me).
How to deploy those resources should decided by the PIs advised by the
group.

**Comment by sofia-bg** [comment]
sounds good, can ask Lori/Karen/Jeff when they would like to discuss this

**Comment by aetkie** [comment]
Trying to make this work now. 
I named the Display "message window" in Layout. 
Then went to Actions and added a new Action
Origin: message window
Conditions: (blank)
State: $Speak
New Value:$Display

works perfectly

**Comment by sofia-bg** [comment]
@aetkie awesome!
