### ISSUE TITLE
conjugateGrid in example 60 is misbehaving

### ISSUE THREAD

**Issue by gbishop** [UNC-Project-Open-AAC/OS-DPI#23]
It is trying to display everything. It didn't do that before. What changed?

**Comment by gbishop** [comment]
Oh, I see what is happening. I opened the design and immediately opened the conjugateGrid in the layout view. It doesn't work properly when activate that way because $lastWord doesn't have a value. 

We need a way to initialize state variables.

**Comment by gbishop** [comment]
I think this is actually working as intended. 

The issue occurs when browsing to the grid in the layout view. The state variable is uninitialized so it tries to include everything. Maybe the issue is actually in layout?

**Comment by sofia-bg** [comment]
I do not understand how yours is working as I examine the actions and compare to my own I do not see where it would know to only supply the relevant morph words mine is not working https://unc-project-open-aac.github.io/OS-DPI/#SBG_60_1_7_22

**Comment by gbishop** [comment]
I will look tomorrow.

**Comment by gbishop** [comment]
I see two minor issues with your design. 

First, in your Actions tab, your 2nd action is triggering on every press on the home_page. We stop searching after the first one we find. So you never make it to that 3rd action. I think you should delete that 2nd one. You can tell which one it is choosing by looking at the Actions tab while you click in the grid. It will show the rule it chose in bold type. 

Next, your morphGrid needs the $lastToken tag to narrow the entries to those that have the last word as their key.

**Comment by sofia-bg** [comment]
Ah so this helps highlight another version control issue on my end, because I had already identified and moved the action 2. Ok thanks will keep plugging away
