### ISSUE TITLE
swap locations in grid

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#26]
It would be useful to quickly swap the contents of buttons in a grid.

**Comment by gbishop** [comment]
I'll need more explanation for what you want.

**Comment by sofia-bg** [comment]
If in your spreadsheet it indicates that "Clear" will be in row 6 column 9 but now you want it in row 6 column 1. 

Is the only way for the move to happen to go back and make the change in the spreadsheet. 

Which if it were a possibility to "move things" in the developer view, would that be able to be exported and reflected in a .csv?

**Comment by gbishop** [comment]
The current way is to go back to your spreadsheet, make the change, and hit
reload. We could have some halfway spreadsheet editing capabilities but I
think it would be a diversion.

**Comment by gbishop** [comment]
Let's leave spreadsheet editing to external programs.
