### ISSUE TITLE
UNDO function 

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#29]
Pressed UNDO when I was in actions tab thinking it would undo the last thing I had done, instead it cleared all of my actions statements. If this is intended function seems like a warning or "are you sure" step is warranted.

**Comment by gbishop** [comment]
That is a bug for sure! It *should* have undone the last thing you did. Did
you, by chance, reload? And could that have been the last thing you did?

**Comment by sofia-bg** [comment]
No the last thing I had done was delete an action, and was hoping it would bring it back.

**Comment by gbishop** [comment]
I can reproduce it. I'll fix as soon as I can figure out what is wrong.

**Comment by gbishop** [comment]
I have uploaded a change that I think fixes this issue.
