### ISSUE TITLE
Reloading sheet/adding information to sheet

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#30]
How does reloading or loading a new version of same sheet work with interface? Initially when we could not download the .csv I just started by loading the data remotely using the url for the raw data. Now I hav downloaded the sheet and wanted to play with adding information for people/places/describing. I added the rows, and everything else is the same, but when I load and even re-load the local sheet I do not see the changes I anticipate. As well, the Content tells me there are still same number of rows as before even though I have added. Is it a problem to mix the input sources then?

**Comment by gbishop** [comment]
OK, I can't seem to reproduce that one. Here's what I did.

I created a new design.
On the content tab I loaded examples/content/36.csv
I added a row to the csv
I hit reload and now I have 37 rows.

Can you give me a similar sequence that breaks?

**Comment by sofia-bg** [comment]
I think the problem was that I initially pulled context from the url and then it wasn't happy with linking a new .csv 

When I created a new design I could update the spreadsheet and reload worked.

**Comment by gbishop** [comment]
That shouldn't cause a problem but I'll give it a try.
