### ISSUE TITLE
Groups pgs.

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#31]
I created a new spreadsheet and started a new interface. I have my modal working, but cannot figure out why my groups buttons aren't opening to pages of the related group data like they are in the example 60. When I press people and look at actions it looks like I have actions tripping in right order. Help?
[Sofia_60_v2.csv](https://github.com/UNC-Project-Open-AAC/OS-DPI/files/7848463/Sofia_60_v2.csv)
 https://unc-project-open-aac.github.io/OS-DPI/#Sofia_60_v2

**Comment by gbishop** [comment]
Please share your .osdpi file just like you did those above.

**Comment by sofia-bg** [comment]
Not sure how else to share it than the url when I drag and drop the file I saved to my desktop it says "we do not support that file type" not sure how I did it differently last time.

**Comment by gbishop** [comment]
Ah, I see. We may have to rethink our suffix... Please rename it changing the suffix to ".zip" which is what they really are.

**Comment by gbishop** [comment]
You need to add a $group tag to your grid, that will tell it to select only those when it is set. 

Then you'll need to clear the $group state variable. I suggest adding it to your 6th action where you add_word and set lastToken. Make the new value of $group be `''` (that is an empty string surrounded by two quotes).

**Comment by sofia-bg** [comment]
Ah add $group to the grid in layout. Was confused by that. 

Got it to work - thanks
