### ISSUE TITLE
Play audio file with a button

### ISSUE THREAD

**Issue by gbishop** [UNC-Project-Open-AAC/OS-DPI#34]
Small speech recordings.

**Comment by gtrogdon** [comment]
@gbishop Currently have made significant progress on this, and am almost done. Have added the ability to import audio recordings in a similar way to images, and I have made my own Audio component (very similar to the speech component). 

But I am running into an issue where the state is not observing when my new $Audio state variable is updating. Is there some initialization step that I am forgetting aside from adding the audio component to components/index.js? I've been poking around the code, but I haven't been able to find whatever step I am missing to get the state to watch $Audio.

**Comment by gbishop** [comment]
Look at components/speech.js. You'll see it has a template even though it
doesn't put anything into the DOM. The trick then is to avoid speaking
(playing the sound) every time anything in the state is updated. This is
handled by state.hasBeenUpdated which will be true if the value has changed
since the last time you looked. It's a hack but the best I could do at the
time.

One more trick, everything in the component tree gets its template invoked
on state updates. You need your audio component to be in the tree. Again
look at speech. You add the speech component to the page, give its state a
name, and then you can use it.

**Comment by gtrogdon** [comment]
Doh! It turns out I had everything correct when I wrote my original post that you laid out above, but I just needed to rebuild using "npm run build," and then the behavior I was expecting occurred. Before rebuilding, it was not detecting when $Audio was updating, even though it was correctly updating that state variable.

**Comment by gbishop** [comment]
You shouldn't have to build in dev mode. Maybe caching somewhere?

I'm really pleased you're working on this. Look at combining it with #25. I
suggest a single store named "media" with images, audio, and anything else
dumped into there. Then add the design name as another key so we can do
queries by design and name. Then we won't have conflicts.

Later we could "optimize" by only storing things once if they are used in
multiple designs but that could wait.

**Comment by gtrogdon** [comment]
I did not think I needed to build in dev mode either, which is why it perplexed me for this long.

And will do! Was already thinking of combining audio and images, especially with the prevalence of db methods such as .addImage or .getImage that could easily be generalized to any kind of media.

**Comment by gtrogdon** [comment]
Have opened a pr to merge fixes for both this issue and #25
