### ISSUE TITLE
Should we change the suffix?

### ISSUE THREAD

**Issue by gbishop** [UNC-Project-Open-AAC/OS-DPI#37]
.zip would allow us to attach to github issues. The downside is users are going to think ANY .zip file can be loaded. 

I'm thinking attaching to issues isn't that important.

**Comment by gtrogdon** [comment]
We could switch over to .zip and implement an internal validator that informs users of .zip files that don't have missing data... but I also don't think attaching to issues is that important. I'd sooner create a way for the program to pull in entire designs from the web and then dropping links to those designs within issues.

**Comment by gbishop** [comment]
The ?fetch=URL syntax will allow fetching from any url, not just relative
ones like examples/36.osdpi. But the other end needs the CORS headers or
the browser will complain.

**Comment by gtrogdon** [comment]
Right. I now remember you experimenting with that.
Which leads us back to github, which I remember you having success with, right? Hmm...

**Comment by gbishop** [comment]
I'm thinking it isn't important enough to change the suffix. If people see
.zip they are going to assume any .zip file will suffice.
