### ISSUE TITLE
Keyboard - speak words?

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#41]
I used the #group to make a keyboard. Might have been a bad choice over a modal because now it is closing every time you select a word but I can work on solutions. 

Current problem is after every letter it puts a space so the speech reads as individual letters. 

https://unc-project-open-aac.github.io/OS-DPI/#Sofia_60_v5
[Sofia_60_v2.csv](https://github.com/UNC-Project-Open-AAC/OS-DPI/files/7864364/Sofia_60_v2.csv)

**Comment by gbishop** [comment]
Yes, we need an add_letter function. I'll hack up one.

**Comment by gbishop** [comment]
I have pushed an update with add_letter. See if that does it for you.

**Comment by sofia-bg** [comment]
Woo hoo - it works!! And I added it to the right place in my actions on the first try!

**Comment by gbishop** [comment]
Awesome!
