### ISSUE TITLE
Can we reduce redundancy in the content?

### ISSUE THREAD

**Issue by gbishop** [UNC-Project-Open-AAC/OS-DPI#42]
In a large sequenced example I built with 5358 rows, 524 rows are required just to keep the CLEAR button in the same place.

Clearly some sort of "don't care" tags could help with that.

**Comment by gbishop** [comment]
Two ideas.

Don't care tags could be an asterisk. Matches anything. This could be generalized if we needed to thinks like A* which matches anything that begins with A. 

We could save a bunch (I think) when we have specified rows and columns in the content by saying it takes the first one that qualifies. 

Then you might have a sheet like this:

| row | col | tag | label |
| --- | ----- | ---- | ---- |
| 1 | 1 | ing | going |
| 1 | 1 | * | go |
| 1 | 2 | * | different |

Here I'm thinking that any prefix such as "I am" would set at state variable used at the tag to "ing" and we'd pick up the "going" form. Anything else would pick up "go". The 1,2 slot gets different regardless.

**Comment by gtrogdon** [comment]
I was thinking about this earlier as well while working on row/col/paging... I like the idea shown in your example, although I'll think on it a little more before working on it.
As it stands, it would save table rows (like you said), and it should be pretty dynamic, especially in the case where you have multiple tags for each entry.

**Comment by gbishop** [comment]
I haven't thought through it enough but I think it would work and bring some great new capability. I like that taking the first one is consistent with the way we handle actions. Picking off special cases and having a final fallback is easy to reason about.

**Comment by gbishop** [comment]
The don't care capability should be in data.js. The grid should handle the first-one wins bit (I think). Maybe getTaggedRows handles it all?

**Comment by gbishop** [comment]
@gtrogdon here's an idea for handling the ordering constraint. 

Include the line number from the incoming sheet in the row structure. Then, when we load the sheet we can sort it by row, column, line number. You won't need the sort in grid because they are already ordered.

**Comment by gtrogdon** [comment]
That sounds good. Shall I go ahead and start mocking this up in a separate branch?

**Comment by gbishop** [comment]
Yes, please!

**Comment by gbishop** [comment]
I wonder if while we're doing this processing on the content if we shouldn't clean it up in that pass? Why not? 

We could force all row, column, page entries to be numbers. Then we wouldn't have to be testing them everywhere. Maybe we choose a distinguished value (like -1) for all of those entries that are undefined.

This would simplify lots of code and make the sorting more efficient.

**Comment by gbishop** [comment]
I'm beginning to think that pre-sorting like I suggested seems wrong. It implies that grid is in a favored position in the components. I'd like to keep that open for future ideas.

I'm going to think about handling this first one wins strategy in grid.
