### ISSUE TITLE
Font size in Display

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#43]
Can we add something to layout tab to change the font size in display?

**Comment by gbishop** [comment]
Yes, that is easily doable.

**Comment by gtrogdon** [comment]
Have implemented this in "font-size" branch. Will merge it somewhere more accessible soon...

**Comment by gbishop** [comment]
No. Now I remember why I wanted it to be unit less like REM. We change the font size depending on the screen size. We don't want a 16px font on a super res monitor.

**Comment by gtrogdon** [comment]
I've gone ahead and changed the units to rem on my fork, and changed the default step size in properties to 0.5, since a step size of 1 is too aggressive.
