### ISSUE TITLE
Color individual button background 

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#44]
Can we change individual button color backgrounds - similar to how if you add a button to a modal then you can manipulate color?

**Comment by sofia-bg** [comment]
Would that give you multiple color options or just one? 
Thinking you would have a color option and name colors otherwise empty defaults to white? 
Pretty common for folks to want to have multiple colored buttons per page. 

Also wondering if option to color the space behind the buttons? An area of interest for AAC is having the space behind buttons and button backgrounds all black.

**Comment by gbishop** [comment]
You could specify a different color for every line in the sheet if you wanted to. Is that what you mean?

Empty defaults to the background color of the grid.

If you set the background color of the grid to black, you'll get black around the images. If you also set the background color of the stack enclosing the grid you'll get black for the missing buttons (we could fix that so they all get background color). We'll need to provide a way to specify the text color is you want to see it.
