### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#45]
Made a numbers group and it wasn't opening on the interface. 
Discovered when label was a numeral it would not appear. 
Changed them to written word with numeral image and that worked. 
Thinking need a way to have numerals so that folks can combine 0-9. 

https://github.com/UNC-Project-Open-AAC/Internal/blob/fcdecbe8c849d4f1f20bcce0a226951c4a7c71cc/Sofia_60_v3.osdpi

**Comment by gbishop** [comment]
That is a bug. Thanks for reporting.

**Comment by gbishop** [comment]
I think this is fixed.
