### ISSUE TITLE
Save vs. export clarification

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#49]
When I am working in a design and succeed at making a solution that works I want to save right then. 
I save and give it a new name, usually updating the version for the sake of helping me remember order. 
But then if I continue to work in the space, I am not working on that version I recently saved exactly. 

That is the previous name remains unless I "load" the version I saved to desktop. 
I am wondering if we need clarification on what it means to "save" and what is preserved while you work/when you are likely to lose work. 

The current "save" feels more like "export" to me. Because I think the assumption is that anything I do is saved locally in the browser until I "unload" a workspace, correct? 

So my trauma with word is causing me to excessively "export" versions to my desktop in hopes of "saving" versions?

**Comment by gbishop** [comment]
Yes, "Save" is really "Export". The intention is that everything is saved
in the app, all the time (barring bugs). Export makes an external record of
the internal state.

Refreshing the browser, or even closing and opening it again shouldn't lose
anything.

Stuff happens. So "Exporting" is good practice.

Should we rename that button Export?

**Comment by gbishop** [comment]
Fixed.
