### ISSUE TITLE
Spacebar

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#50]
Cannot figure out a space bar - would there need to be an add_space function like there is for add_word and add_letter?

**Comment by gbishop** [comment]
Doesn't "add_letter(' ')" work?

I *think* that if you make the value of a cell be a single space (hard to
see in the spreadsheet), it should work just like any other letter.`

**Comment by sofia-bg** [comment]
Will try. After writing was able to get 'Delete' button to work by using "replace_last('')" just hadn't tried it with space. 

Did notice that with delete it only will delete one word because there is only one "last token" not sure if it matters or how then it would handle deleting letters/words from keyboard

**Comment by gbishop** [comment]
We'll likely need a few more functions (or tweaks to the ones we have) to
get it right.
