### ISSUE TITLE
apostrophe 

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#51]
Apostrophe in spreadsheet did not appear as one in the label on the user interface. 

System replaced with symbol instead.

**Comment by gtrogdon** [comment]
@gbishop, I figured out it was due to the defaults of SheetJS.
Here is the issue related to this problem: https://github.com/SheetJS/sheetjs/issues/2036
I've pushed this change to my fork of the repo. Will make a PR soon.

**Comment by gbishop** [comment]
Great, thanks!

**Comment by gbishop** [comment]
I believe Graham has fixed this.
