### ISSUE TITLE
"or" statement in conditions

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#55]
I thought I remembered that we could use or statements in conditions, but could not figure out how. 

For the keyboard I have it set up as two separate groups for upper and lower and I wanted to use add_letter(#label) for both, and ended up with two separate actions. 

Tried condition where group = 'kb' or group = 'CAPS' 
Tried two conditions one for each (but assume that means both conditions must be true?) 

I assume this all resolves if I figure out a tag system where both are in the group kb but upper case are tagged 1 and lower tagged 2 then I just need one action with the condition group = 'kb' for the add_letter(#label). But there might be other times when we would want an action to apply to one thing or another.

**Comment by gbishop** [comment]
We could support OR but my original thought was you'd just have 2 actions
to pick off the 2 possibilities.

**Comment by sofia-bg** [comment]
Two actions worked just fine, just wanted to make sure I wasn't making more actions if there was a more efficient way
