### ISSUE TITLE
linking VSD within one UI

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#57]
How would we link multiple images in a VSD UI? 

Same Puppies example, tried to link to a new image with groups, but probably not the right solution. 

Added images I was using to the folder with the csv and osdpi [here](https://github.com/UNC-Project-Open-AAC/OS-DPI/tree/main/vsd)

**Comment by gbishop** [comment]
You should be able to use tags to select images and rectangles. I started
on a qwerty keyboard based on an image will try to get it done.
