### ISSUE TITLE
x/y coordinates in VSD

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#58]
Any chance we could see the x/y axis in the design interface once we add a VSD area? 

Wasn't too hard to realize Y actually works down not up, and to play around with updating .csv and seeing where the hotspot moves around on screen, but would be a bit easier with something to anchor.

**Comment by aetkie** [comment]
I second this request. @gbishop and I spoke about this on 12/13 and I recall him saying it was possible. Or, where the cursor hovers, the x/y coordinates could appear

**Comment by sofia-bg** [comment]
looks great!
