### ISSUE TITLE
multiple grids row column references

### ISSUE THREAD

**Issue by lageist** [UNC-Project-Open-AAC/OS-DPI#61]
How do you define the row column location in the spreadsheet for a design with multiple grids on page? For example, grid 1 = row 1-7/column 1-12, grid 2 = row 8-12, column 1-12. Tried defining that way, and tried defining per grid, without success getting things loaded where I want them.

**Comment by gbishop** [comment]
Use tags to separate the content. For example, I'm working on one with a predictions grid on the top and a keyboard grid below. In the Tags property on the top grid control I have the first tag set to "prediction" and the second tag set to "$prefix". Only lines from my content with prediction in the first tag will get routed to this grid. Similarly, in the 2nd grid, I've got the first tag set to "kb", and the second tag set to "$group". 

Does that help?

**Comment by lageist** [comment]
Yes! Thanks, have this set now. On the the next ...
