### ISSUE TITLE
Image error on UI cell

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#73]
When you have the name of a symbol in your spreadsheet, but no corresponding symbol loaded to design interface, you get the image of a missing image on that cell. 

![Screen Shot 2022-02-14 at 2 42 02 PM](https://user-images.githubusercontent.com/92817124/153934939-f6bb988a-f979-47be-95cd-85f0d9197fee.png)

I am wondering if there is a way that could disappear when you press d and toggle to UI only?

**Comment by gbishop** [comment]
I've got a patch for this, I'll push it soon.
