### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#97]
Requests at community meeting to: 

- change text size on button 
- change font in display bar and on button 
- change location of text on button (below or above) 
- change text in display bar to wrap vs. push text off screen

**Comment by gbishop** [comment]
All of these are easy. The major question is where to put them in the interface. I don't want to crowd the editor with lots of fields.

Maybe make the editor a tab control with another page (possibly scrolling) for appearance? 

Another possibility would be enable specifying this stuff at the top level (say on the page) and everything inherits.
