### ISSUE TITLE
VSD Hotspots 

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#98]
Would it be possible to add feature to VSD so that hot spots can be drug around screen and/or size can be manipulated so that you can drag from corner. 

Would this data then be exported to spreadsheet or would spreadsheet export retain initial coordinates?

**Comment by gbishop** [comment]
Now that we have context export this is a very reasonable ask. Though I can see it getting painful. 

Say you're working on your project and spend lots of time getting your hot spots just like you want them. Then you notice you misspelled a word, jump over to your spreadsheet, fix it, and reload. Boom, your updates are gone. 

We could check for modifications to the content and complain when you're about the reload that you're going to lose work.
